### ISSUE TITLE
Programar controle por toque de tela

### ISSUE THREAD

**Issue by lauthjoao** [ja-on1/Joao-Maria-The-order-of-warder#26]
- [x] Pesquisar por sprites genéricos;
- [x]  Importar os sprites no jogo;
- [x]  Associar os sprites a botões de controle;
- [x]  Relacionar os botões de controle a movimentos de personagens e animações.

Depende de #25. Referencia [OpenGameArt](https://opengameart.org/)

**Comment by mariahammes** [comment]
Está na cena principal.
