### ISSUE TITLE
Programar sons de efeito gerados por eventos do jogo

### ISSUE THREAD

**Issue by mariahammes** [ja-on1/Joao-Maria-The-order-of-warder#32]

**Comment by lauthjoao** [comment]
- [ ] Pesquisar por sons de efeito;
- [ ] Importar sons de efeito no jogo;
- [ ] Programar sons de efeito em eventos do jogo como colisão, tempo etc.

**Comment by lauthjoao** [comment]
Som inicial: som de metal, som de fundo outros serão adicionados conformes as coisas forem postas
