### ISSUE TITLE
Definir hospedagem do jogo

### ISSUE THREAD

**Issue by mariahammes** [ja-on1/Joao-Maria-The-order-of-warder#35]

**Comment by mariahammes** [comment]
- [ ] Conteúdo estático: apenas HTTP
- [ ] Conteúdo dinâmico: WebSocket

Depende de #14

**Comment by mariahammes** [comment]
A nuvem pública adotada é [AWS]

**Comment by lauthjoao** [comment]
Decidido que haverá 3 níveis de infraestrutura:

Nível básico (nota 6): virtualização plena;
Nível intermediário (nota 8): contêiner;
Nível avançado (nota 10): serverless.
