### ISSUE TITLE
Estudar DNS

### ISSUE THREAD

**Issue by mariahammes** [ja-on1/Joao-Maria-The-order-of-warder#36]

**Comment by lauthjoao** [comment]
- [ ] Domínio;
- [ ] Servidores raiz (root servers);
- [ ] Delegação de autoridade;
- [ ] TLD;
- [ ] ccTLD;
- [ ] RR (resource record);

**Comment by mariahammes** [comment]
Assistir gravação + sites (link no sigaa).
